<?php
// $Id: pg_account_paypal.module,v 1.1 2010/10/28 01:51:44 gor Exp $

/********************************************************************
 * Pg_account Gateway Hooks
 ********************************************************************/
function pg_account_paypal_pgaccount_withdraw($op,$a3=NULL,$a4=NULL){
  global $user;
  switch($op){
    case 'display name':
        $ret = t('PayPal');
      break;
    case 'get form':
        $form_result = $a3;
        $ret = pg_account_paypal_form($form_result);
      break;
    case 'operator form':
        $ret = pg_account_paypal_operatorForm($a3);
      break;      
  }
  return $ret;
}
/********************************************************************
 * Callback Functions
 ********************************************************************/
 
function pg_account_paypal_form(){

  $form['email'] = array(
    '#type'          => 'textfield',
    '#title'         => t('E-mail'),
    '#description'   => t("Please, enter PayPal email."),
    '#default_value' => $res->email,
    '#required'      => TRUE,
    '#size'          => 15,
  );
  return $form;
}

function pg_account_paypal_operatorForm($t){
  $form['purse'] = array(
    '#type'          => 'markup',
    '#value'         => t('E-mail').': '.$t->extra['email'].'<br>',
  );
  return $form;
}

/********************************************************************
 * Functions theme
 ********************************************************************/
