<?php
// $Id: pg_account_rubank.module,v 1.1 2010/10/28 01:51:44 gor Exp $

/********************************************************************
 * Pg_account Gateway Hooks
 ********************************************************************/
function pg_account_rubank_pgaccount_withdraw($op,$a3=NULL,$a4=NULL){
  global $user;
  switch($op){
    case 'display name':
        $ret = t('Russian bank');
      break;
    case 'get form':
        $form_result = $a3;
        $ret = pg_account_rubank_form($form_result);
      break; 
    case 'operator form':
        $ret = pg_account_rubank_operatorForm($a3);
      break;      
           
  }
  return $ret;
}
/********************************************************************
 * Callback Functions
 ********************************************************************/
function pg_account_rubank_form(){

  $form['FIO'] = array(
    '#type'          => 'textfield',
    '#title'         => t('First Last name'),
    '#description'   => t("Your first and last name."),
    '#default_value' => $res->FIO,
    '#required'      => TRUE,
  );
  $form['INN'] = array(
    '#type'          => 'textfield',
    '#title'         => t('INN'),
    '#description'   => t("Bank receiver INN."),
    '#default_value' => $res->IIN,
    '#required'      => TRUE,
  );
  $form['BIK'] = array(
    '#type'          => 'textfield',
    '#title'         => t('BIK'),
    '#description'   => t("Bank receiver BIK."),
    '#default_value' => $res->BIK,
    '#required'      => TRUE,
  );
  $form['name'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Bank name'),
    '#description'   => t("Bank receiver name."),
    '#default_value' => $res->name,
    '#required'      => TRUE,
  );
  $form['kor_account'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Correspondent account'),
    '#description'   => t("Bank receiver Correspondent account"),
    '#default_value' => $res->kor_account,
  );
  $form['ras_account'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Current account'),
    '#description'   => t("Receiver current account."),
    '#default_value' => $res->ras_account,
    '#required'      => TRUE,
  );
  $form['lic_account'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Personal account'),
    '#description'   => t("Receiver personal account."),
    '#default_value' => $res->lic_account,
  );
  
  return $form;
}

function pg_account_rubank_operatorForm($t){
  $form['FIO'] = array(
    '#type'          => 'markup',
    '#value'         => t('First Last name').': '.$t->extra['FIO'].'<br>',
  );
  $form['INN'] = array(
    '#type'          => 'markup',
    '#value'         => t('INN').': '.$t->extra['INN'].'<br>',
  );
  $form['BIK'] = array(
    '#type'          => 'markup',
    '#value'         => t('BIK').': '.$t->extra['BIK'].'<br>',
  );
  $form['name'] = array(
    '#type'          => 'markup',
    '#value'         => t('name of bank').': '.$t->extra['name'].'<br>',
  );
  $form['kor_account'] = array(
    '#type'          => 'markup',
    '#value'         => t('kor_account in bank').': '.$t->extra['kor_account'].'<br>',
  );
  $form['ras_account'] = array(
    '#type'          => 'markup',
    '#value'         => t('ras_account in bank').': '.$t->extra['ras_account'].'<br>',
  );
  $form['lic_account'] = array(
    '#type'          => 'markup',
    '#value'         => t('lic_account in bank').': '.$t->extra['lic_account'].'<br>',
  );
  return $form;
}
